name: Deploy via SCP

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Check hostname resolution
        run: |
          echo "Resolving host:" ${{ secrets.SCP_HOSTNAME }}
          nslookup ${{ secrets.SCP_HOSTNAME }}

      - name: Ping server (IPv4)
        run: ping -c 4 -4 ${{ secrets.SCP_HOSTNAME }}

      - name: Copy files via SCP
        run: |
          sshpass -p "${{ secrets.SCP_PASSWORD }}" \
          scp -o StrictHostKeyChecking=no -r ./ \
          ${{ secrets.SCP_USER }}@${{ secrets.SCP_HOSTNAME }}:
