name: Deploy via SCP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build static site
        run: npm run build
        env:
          PUBLIC_BASE_PATH: /mi_olimpia
          WEB3FORMS_ACCESS_KEY: ${{ secrets.WEB3FORMS_ACCESS_KEY }}

      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Check hostname resolution
        run: |
          echo "Resolving host:" ${{ secrets.SCP_HOSTNAME }}
          nslookup ${{ secrets.SCP_HOSTNAME }} || true

      - name: Copy files via SCP
        run: |
          sshpass -p "${{ secrets.SCP_PASSWORD }}" \
          scp -o StrictHostKeyChecking=no -r ./build/* \
          ${{ secrets.SCP_USER }}@${{ secrets.SCP_HOSTNAME }}:${{ secrets.SCP_TARGET_DIR }}